services:
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass $REDIS_PASSWORD
  app:
    build: .
    depends_on:
      - redis
    ports:
      - '3000:3000'

volumes:
  redis_data:
